# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - PostNApp-UI

pr:
  branches:
    include:
    - master
  paths:
    include:
    - PostNApp-UI

variables:
  appDir: PostNApp-UI

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: node 14
  inputs:
    versionSpec: '14.x'

- script: npm ci
  displayName: npm install
  workingDirectory: $(appDir)

- script: npx ng build
  displayName: ng build
  workingDirectory: $(appDir)

- script: npx ng test --browsers ChromeHeadless --watch false --code-coverage
  displayName: ng test
  workingDirectory: $(appDir)
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-dutran'
    organization: 'dudutran'
    scannerMode: 'CLI'
    configMode: 'manual'
    projectKey: 'dudutran_WebAPI-Angular-Project'
    cliSources: '$(appDir)/src'
    extraProperties: |
      sonar.javascript.lcov.reportPaths=$(appDir)/coverage/$(appDir)/lcov.info
      sonar.coverage.exclusions=**/*.spec.ts
- task: SonarCloudAnalyze@1
  displayName: sonar run analysis

- task: SonarCloudPublish@1
  displayName: sonar publish analysis result
  inputs:
    pollingTimeoutSec: '300'

